# Generated by Django 5.0.14 on 2026-07-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_transaction_device_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('auto_generated', 'Auto Generated'), ('reviewed', 'Reviewed'), ('filed', 'Filed')], default='auto_generated', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_report', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SARReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('reason', models.TextField()),
                ('narrative', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_reports', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='StructuringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('window_hours', models.IntegerField(default=24)),
                ('transaction_count', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('individual_amounts', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('false_positive', 'False Positive'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structuring_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
